### PR TITLE
Patch1

### PR DESCRIPTION
**Pull request by roshankcjha**
# Pull Request.

Kindly adhere to the template!

Generate a Pull Request if the code fixes an **issue**, or if you feel that the change is **important** and the world would stop spinning without it.

## Description

So this Pull request lists out the files in Python required for implementing Merge Sort operation and solving Tower of Hanoi Problem through Recursion.It can solve issue #3 as well as introduced some new content

Fixes #(issue)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to change).
- [ ] This change requires a documentation update.
- [x] The code follows the code style of this project.
- [ ] Documentation has been updated accordingly.
- [ ] Tests have been added to cover the changes.
- [x] All new and existing tests passed.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:

- Firmware version:
- Hardware:
- Toolchain:
- SDK:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

---

### CODE REVIEW

**Comment by roshankcjha** [comment]
@cipheraxat  @hritikbhandari  and other maintainers of the Github Repository kindly review this PR and provide the required reviews if needed.

**Comment by cipheraxat** [comment]
Hey @roshankcjha also update the basicquestion.md file with question name with hyperlink of that question

**Comment by roshankcjha** [comment]
@cipheraxat should I do it for both merge sort implementation and Tower of Hanoi problem or only for merge sort implementation because Tower of Hanoi problem is known in general by all?

**Comment by roshankcjha** [comment]
It's done @cipheraxat . You can view them out and provide the reviews

**Review by cipheraxat — APPROVED** [review]

**Pull request merged**
